# Docker Compose Local Development Setup
#
# This starts a local multi-container development environment
# with Postgres, Redis, Celery, and Django.
# The configuration comes from .envs/local
#
# To run:
#   $ make dockerbuild
#   $ make dockerserve

version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker-compose/local/django/Dockerfile
    image: ethicaladserver_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/local/django
      - ./.envs/local/postgres
    ports:
      - "5000:5000"
    command: /start
    # Allow us to run `docker attach` and get
    # control on STDIN and be able to debug our code with interactive pdb
    stdin_open: true
    tty: true

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celeryworker:
    <<: *django
    image: ethicaladserver_local_celeryworker
    depends_on:
      - redis
      - postgres

    env_file:
      - ./.envs/local/django
      - ./.envs/local/postgres

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ethicaladserver_local_celerybeat
    depends_on:
      - redis
      - postgres

    env_file:
      - ./.envs/local/postgres
      - ./.envs/local/django

    ports: []
    command: /start-celerybeat

  frontend:
    build:
      context: .
      dockerfile: ./docker-compose/local/frontend/Dockerfile
    ports: []
    volumes:
      - .:/app
